apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f ./backend/game/docker-compose.yml -o ./backend/game/charts/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: game
  name: game
spec:
  ports:
  - name: "4100"
    port: 4100
    targetPort: 4100
  selector:
    io.kompose.service: game
status:
  loadBalancer: {}
